name = "space-maze"
compatibility_date = "2024-04-03"
pages_build_output_dir = "dist"

[env.production]
name = "space-maze-production"
compatibility_date = "2024-04-03"

[vars]
# Add environment variables here
